name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'Hexoni.zip'
          exclusions: '*.git*'
      - name: Sha1sum
        run: 'sha1sum Hexoni.zip | cut -f 1 -d " " > sha1.txt'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'Hexoni.zip,sha1.txt'
          token: ${{ secrets.TOKEN_GITHUB }}
