name: Zip Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Hexoni.zip"
          token: ${{ secrets.TOKEN_GITHUB }}
