# This is a basic workflow to help you get started with Actions

name: CI

env:
  ## Sets environment variable
  API_KEY: XXXXXXXXXXXX    
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: action-zip
      uses: montudor/action-zip@v1.0.0
      with:
       args: zip -qq -r Hexoni.zip src/
    - uses: actions/checkout@v1
    - name: sha-1-checksum
      run: |
        sha1sum Hexoni.zip > sha1.txt
          - name: check for changes
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating sha1.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
